stages:
    - build-stage
    - test-stage
    - bench-stage

build:
    image: haskell:9.2-slim-buster
    stage: build-stage
    needs: []
    artifacts:
        paths:
            - haskell-parsing-benchmarks
            - haskell-parsing-benchmarks-tests
            - big-example.txt
        expose_as: 'benchmark-executables'
        expire_in: 3 days
    cache:
        key: cabal-store
        paths:
            - cabal-store/

    before_script:
        - apt-get update && apt-get install -y llvm-11-tools clang-11 python3
        - cabal update
        - export PATH=/usr/lib/llvm-11/bin:$PATH

    script:
        - cabal --store-dir=cabal-store build --enable-benchmarks --allow-newer
        - python3 ./gen-example.py

    after_script:
        - cp "$(cabal list-bin bench:haskell-parsing-benchmarks)" haskell-parsing-benchmarks
        - cp "$(cabal list-bin test-suite:haskell-parsing-benchmarks-tests)" haskell-parsing-benchmarks-tests

test:
    image: debian:buster-slim
    stage: test-stage
    needs: ["build"]
    artifacts:
        paths:
            - results-tests.txt
        expose_as: test-results

    script:
        - ./haskell-parsing-benchmarks-tests | tee results-tests.txt

bench:
    image: debian:buster-slim
    stage: bench-stage
    needs: ["build"]
    artifacts:
        paths:
            - results-time.txt
            - results-mem.txt
        expose_as: benchmark-results

    script:
        - ./haskell-parsing-benchmarks --stdev 5 --timeout 60 | tee results-time.txt
        - ./peak-memory.sh haskell-parsing-benchmarks | tee results-mem.txt
